name: Go

on:
  push:
    branches:
      - master 
      - test
  pull_request:
    branches:
      - master

jobs:

  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    # 执行 go build
    - name: Build
      run: go build -v ./...
    # 执行go test
    - name: Test
      run: go test -v ./...
